enable-barrel-catch: true
barrel-catch-chance: 10.0 # Hook Item Replacement Chance (0.0 - 100.0)
items:
  - material: enchantment_book
    chance: 10
    enchants:
      - mending:
          chance: 10
      - oxygen:
          level: 1-5
          chance: 10
  - material: enchantment_book
    chance: 10
    enchants:
      - sharpness:
          level: 1-5
          chance: 20
  - material: mace
    chance: 5
    name: <aqua>Old Traveler's Mace
    lore:
      - <yellow>Most likely belonged to one of the <red>Ruby Horizon<yellow> travelers.
    cmd: 1
    enchants:
      - sharpness:
          level: 1-3
          chance: 10
  - material: bone_meal
    count: 1-4
    chance: 25.0
  - material: paper
    count: 1-4
    chance: 13.0
  - material: bone
    count: 3-13
    chance: 50.0
  - material: red_mushroom
    count: 15-16
    chance: 2.0
  - material: coal
    count: 4-12
    chance: 41.0
  - material: gunpowder
    count: 9-20
    chance: 4.0
  - material: string
    count: 2-11
    chance: 7.0
  - material: bowl
    count: 1-2
    chance: 1.0
  - material: potato
    count: 21-53
    chance: 57.0
  - material: glowstone_dust
    count: 11-12
    chance: 7.0

  # ItemsAdder item example
  # - material: "ia:namespace:item_id"
  # count: 1
  # chance: 10

  # MMOItems item example
  # - material: "mmo:namespace:item_id"
  # count: 1
  # chance: 50

