# Please let me know if you find any errors/bugs in the plugin:
#   https://www.spigotmc.org/members/shershnyaga_.1502182/
lang-file: eng.yml
auto-update: true # Doesn't work on Windows!
dolphin-catch-chance: 2.0 # 0.0 - 100.0