name: BetterCallFishing
version: '${version}'
main: me.sherhsnyaga.bettercallfishing.BetterCallFishing
api-version: '1.16'
load: STARTUP
authors: [ Shershnyaga_ ]
website: shershnyaga.xyz
commands:
  bettercallfishing:
    usage: /bettercallfishing <args>
permissions:
  bettercallfishing.*:
    default: op
    children:
      - bettercallfishing.reload
      - bettercallfishing.barrels
  bettercallfishing.reload:
    default: op
    description: Grant permission to /bettercallfishing reload command
  bettercallfishing.barrels:
    default: op
    description: Grant permission to /bettercallfishing gen_barrel command